on:
    workflow_dispatch

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
        actions: write
    steps:
      - uses: actions/checkout@v4

      - run: |
            gh variable list
            gh variable set TEST_VAR --body "Set from workflow"
            gh variable list
