on: [workflow_dispatch, push]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
        actions: write
    steps:
      - uses: actions/checkout@v4
      - run: |
            gh variable set TEST_VAR1 --body "Set from workflowdfg"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
